AteneoHighschool.Admin/Controllers/CurriculumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web.Mvc;
using AteneoHighschool.Data;
using AteneoHighschool.DataAccess;

namespace AteneoHighschool.Admin.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class CurriculumController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();
        private readonly GenericRoleProvider _roleProvider = new GenericRoleProvider();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetListJson(DataTableParamVM param)
        {
            try
            {
                Thread.Sleep(200);

                string sortProperty;
                string searchText = (!string.IsNullOrEmpty(param.sSearch)) ? param.sSearch : "";

                switch (param.iSortCol_0)
                {
                    case 1: sortProperty = "CurriculumName"; break;
                    default: sortProperty = "CurriculumName"; break;
                }

                var curriculum = _unitOfWork.CurriculumRepository.GetList(q => q.CurriculumName.Contains(searchText),
                    iDisplayStart: param.iDisplayStart, iDisplayLength: param.iDisplayLength, sortProperty: sortProperty,
                    sortOrder: param.sSortDir_0, includeProperties: "AcademicYear, Course");

                var recordCount = _unitOfWork.CurriculumRepository.Get().Count();

                return Json(new
                {
                    param.sEcho,
                    iTotalRecords = recordCount,
                    iTotalDisplayRecords = recordCount,
                    aaData = curriculum
                },
                  JsonRequestBehavior.AllowGet);

            }
            catch (ArgumentException ae)
            {
                ModelState.AddModelError("", ae.Message);
                return Json(new { success = false, error = GetErrorsFromModelState() });
            }
        }

        [HttpPost]
        public JsonResult GetListJson(string searchText, int maxResult)
        {
            var curriculumList =
                _unitOfWork.CurriculumRepository.GetList(q => q.CurriculumName.Contains(searchText),
                    iDisplayLength: maxResult).Select(q => new {id = q.CurriculumId, label = q.CurriculumName});
            return Json(curriculumList);
        }

        public ActionResult Create()
        {
            if (_roleProvider.IsUserInUserRole(User.Identity.Name, "Administrator"))
            {
                var curriculum = new Curriculum
                {
                    CurriculumName = null
                };
                return PartialView(CurriculumVm(curriculum));
            }
            ViewBag.ProhibitedMessage = "Sorry! You have no right to create a new Curriculum.";
            return PartialView("_Prohibited");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CreateJson(Curriculum curriculum)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { success = false, error = GetErrorsFromModelState() });
                }

                _unitOfWork.CurriculumRepository.Insert(curriculum);
                Guid curriculumGuid = curriculum.CurriculumId;
                curriculum = _unitOfWork.CurriculumRepository.GetOne(q => q.CurriculumId == curriculumGuid);

                return
                    Json(
                        new
                        {
                            success = true,
                            message = "You have successfully created a new Curriculum: " + curriculum.CurriculumName
                        });
            }
            catch (ArgumentException ae)
            {
                ModelState.AddModelError("",
                    "Creation of new Curriculum failed.Please check if there is already an existing Curriculum: " +
                    curriculum.CurriculumName + "." + ae.Message);
                return Json(new { success = false, error = GetErrorsFromModelState() });
            }
        }

        public ActionResult Edit(Guid id)
        {
            if (_roleProvider.IsUserInUserRole(User.Identity.Name, "Administrator"))
            {
                Curriculum curriculum = _unitOfWork.CurriculumRepository.GetOne(q => q.CurriculumId == id);
                return PartialView(CurriculumVm(curriculum));
            }
            ViewBag.ProhibitedMessage = "Sorry! You have no right to edit a Curriculum.";
            return PartialView("_Prohibited");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult EditJson(Curriculum curriculum)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { success = false, error = GetErrorsFromModelState() });
                }

                _unitOfWork.CurriculumRepository.Update(curriculum);

                return
                    Json(
                        new
                        {
                            success = true,
                            message = "You have successfully edited a Curriculum: " + curriculum.CurriculumName
                        });
            }
            catch (ArgumentException ae)
            {
                ModelState.AddModelError("",
                    ae.Message + "Please check if there is already a Curriculum named: " + curriculum.CurriculumName +
                    ".");
                return Json(new { success = false, error = GetErrorsFromModelState() });
            }
        }

        public ActionResult Delete(Guid id)
        {
            if (_roleProvider.IsUserInUserRole(User.Identity.Name, "Administrator"))
            {
                Curriculum curriculum = _unitOfWork.CurriculumRepository.GetOne(r => r.CurriculumId == id);
                return PartialView(CurriculumVm(curriculum));
            }
            ViewBag.ProhibitedMessage = "Sorry! You have no right to delete a Curriculum.";
            return PartialView("_Prohibited");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteJson(Curriculum curriculum)
        {
            try
            {
                _unitOfWork.CurriculumRepository.Delete(curriculum);

                return
                    Json(
                        new
                        {
                            success = true,
                            message = "You have successfully deleted a Curriculum: " + curriculum.CurriculumName
                        });
            }
            catch (ArgumentException ae)
            {
                ModelState.AddModelError("", ae.Message);
                return Json(new { success = false, error = GetErrorsFromModelState() });
            }
        }

        [ActionName("Detail")]
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Detail(Guid id)
        {
            if (_roleProvider.IsUserInUserRole(User.Identity.Name, "Administrator"))
            {
                Curriculum curriculum = _unitOfWork.CurriculumRepository.GetOne(q => q.CurriculumId == id);
                return PartialView(CurriculumVm(curriculum));
            }
            ViewBag.ProhibitedMessage = "Sorry! You have no right to view a Curriculum.";
            return PartialView("_Prohibited");
        }

        public ActionResult CurriculumItems(Guid curriclumId)
        {
            var curriculumItem = _unitOfWork.CurriculumItemRepository.GetList(q => q.CurriculumId == curriclumId,
                includeProperties: "Curriculum, Curriculum.AcademicYear, ProficiencyLevel");

            return PartialView("_CurriculumItem", curriculumItem);
        }

        public CurriculumVM CurriculumVm(Curriculum curriculum)
        {
            var curriculumVm = new CurriculumVM
            {
                Curriculum = curriculum,
                AcademicYearVM = new AcademicYearVM
                {
                    AcademicYear = curriculum.AcademicYear,
                    AcademicYearList =
                        new SelectList(_unitOfWork.AcademicYearRepository.GetList().OrderBy(ay => ay.AcademicYearName),
                            "AcademicYearId", "AcademicYearName")
                },
                CourseVM = new CourseVM
                {
                    Course = curriculum.Course,
                    CourseList = 
                        new SelectList(_unitOfWork.CourseRepository.GetList().OrderBy(c => c.CourseName),
                            "CourseId", "CourseName")
                }
            };
            return curriculumVm;
        }

        private IEnumerable<string> GetErrorsFromModelState()
        {
            return ModelState.SelectMany(x => x.Value.Errors.Select(error => error.ErrorMessage));
        }

        protected override void Dispose(bool disposing)
        {
            _unitOfWork.Dispose();
            base.Dispose(disposing);
        }
    }
}

AteneoHighschool.Admin/Views/Curriculum/Create.cshtml
@model AteneoHighschool.Data.CurriculumVM

@{
    ViewBag.Title = "Create";
}
<script type="text/javascript">
    $(document).ready(function () {
        $(".date-picker").datepicker({
            dateFormat: 'DD, d MM, yy',
            firstDay: 1,
            changeMonth: true,
            changeYear: true,
            showWeek: true
        });
    });
</script>
@using (@Html.BeginForm("CreateJson", "Curriculum", FormMethod.Post, new { @id = "CreateCurriculumForm" }))
{
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

    <fieldset class="ui-form">
        <div class="editor-label">
            @Html.LabelFor(model => model.Curriculum.CurriculumName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Curriculum.CurriculumName)
            @Html.ValidationMessageFor(model => model.Curriculum.CurriculumName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Curriculum.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Curriculum.Description)
            @Html.ValidationMessageFor(model => model.Curriculum.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Curriculum.StartDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Curriculum.StartDate)
            @Html.ValidationMessageFor(model => model.Curriculum.StartDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Curriculum.EndDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Curriculum.EndDate)
            @Html.ValidationMessageFor(model => model.Curriculum.EndDate)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Curriculum.AcademicYear)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Curriculum.AcademicYearId, Model.AcademicYearVM.AcademicYearList, "")
            @Html.ValidationMessageFor(model => model.Curriculum.AcademicYearId)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Curriculum.Course)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Curriculum.CourseId, Model.CourseVM.CourseList, "")
            @Html.ValidationMessageFor(model => model.Curriculum.CourseId)
        </div>
    </fieldset>
}
<script src="@Url.Content("~/Content/Js/Curriculum/Create.js")" type="text/javascript"></script>

AteneoHighschool.Admin/Views/Curriculum/Delete.cshtml
@model AteneoHighschool.Data.CurriculumVM

@using (@Html.BeginForm("DeleteJson", "Curriculum", FormMethod.Post, new {@id = "DeleteCurriculumForm"}))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Curriculum.CurriculumId)

    <h3>Are you sure you want to delete this?</h3>
    <fieldset class="ui-form">
        <div>
            @Html.DisplayNameFor(model => model.Curriculum.CurriculumName) :
        </div>
        <div>
            @Html.DisplayFor(model => model.Curriculum.CurriculumName)
        </div>

        <div>
            @Html.DisplayNameFor(model => model.Curriculum.Description) :
        </div>
        <div>
            @Html.DisplayFor(model => model.Curriculum.Description)
        </div>

        <div>
            @Html.DisplayNameFor(model => model.Curriculum.StartDate) :
        </div>
        <div>
            @Html.DisplayFor(model => model.Curriculum.StartDate)
        </div>

        <div>
            @Html.DisplayNameFor(model => model.Curriculum.EndDate) :
        </div>
        <div>
            @Html.DisplayFor(model => model.Curriculum.EndDate)
        </div>
    </fieldset>
}
<script src="@Url.Content("~/Content/Js/Curriculum/Delete.js")" type="text/javascript"></script>

AteneoHighschool.Admin/Views/Curriculum/Detail.cshtml
@model AteneoHighschool.Data.CurriculumVM

@{
    ViewBag.Title = string.Format("Curriculum: {0}", Model.Curriculum.CurriculumName);
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/themes/default/jquery-ui-1.10.3.custom.css")" media="all" />
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.9.1.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery-ui-1.10.3.custom.min.js")"></script>
<script>
    $(function () {
        $("#tabs").tabs();
    });
</script>

<h2>@ViewBag.Title</h2>
<div id="tabs">
    <ul>
        <li><a href="#detail-tab">Details</a></li>
        <li><a href="#curriculum-item-tab">Curriculum Items</a></li>
    </ul>
    <div id="detail-tab">
        @{
            <div class="ui-widget-header ui-tool-bar">
                <a href="@Url.Action("Index", "Curriculum")" title="Click this Icon to View Curriculums" class="uiButton">Back</a>
            </div>
            <div class="ui-form">
                @Html.Partial("_Detail", Model)
            </div>
        }
    </div>

    <div id="curriculum-item-tab" style="font-size: 18px">Subject Items</div>
    <div>
        @{
            Html.RenderAction("CurriculumItems", "Curriculum", new { curriclumId = Model.Curriculum.CurriculumId});
        }
    </div>
</div>

AteneoHighschool.Admin/Views/Curriculum/Edit.cshtml
@model AteneoHighschool.Data.CurriculumVM

@{
    ViewBag.Title = "Edit";
}
<script type="text/javascript">
    $(document).ready(function () {
        $(".date-picker").datepicker({
            dateFormat: 'DD, d MM, yy',
            firstDay: 1,
            changeMonth: true,
            changeYear: true,
            showWeek: true
        });
    });
</script>
@using (@Html.BeginForm("EditJson", "Curriculum", FormMethod.Post, new { @id = "EditCurriculumForm" }))
{
         @Html.AntiForgeryToken()
         @Html.ValidationSummary(true)
         @Html.HiddenFor(model => model.Curriculum.CurriculumId)

    <fieldset class="ui-form">
        <div class="editor-label">
            @Html.LabelFor(model => model.Curriculum.CurriculumName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Curriculum.CurriculumName)
            @Html.ValidationMessageFor(model => model.Curriculum.CurriculumName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Curriculum.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Curriculum.Description)
            @Html.ValidationMessageFor(model => model.Curriculum.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Curriculum.StartDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Curriculum.StartDate)
            @Html.ValidationMessageFor(model => model.Curriculum.StartDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Curriculum.EndDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Curriculum.EndDate)
            @Html.ValidationMessageFor(model => model.Curriculum.EndDate)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Curriculum.AcademicYear)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Curriculum.AcademicYearId, Model.AcademicYearVM.AcademicYearList, "")
            @Html.ValidationMessageFor(model => model.Curriculum.AcademicYearId)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Curriculum.Course)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Curriculum.CourseId, Model.CourseVM.CourseList, "")
            @Html.ValidationMessageFor(model => model.Curriculum.CourseId)
        </div>
    </fieldset>
}
<script src="@Url.Content("~/Content/Js/Curriculum/Edit.js")" type="text/javascript"></script>

AteneoHighschool.Admin/Views/Curriculum/Index.cshtml
@{
    ViewBag.Title = "CURRICULUM MANAGEMENT";
}
<h2>@ViewBag.Title</h2>
<div>
    <span data-dialog-title="Create Curriculum" data-url="Curriculum/Create" data-id="CreateCurriculumDialog" class="uiButton" data-process-button="Create" onclick="loadAndShowDialog($(this))">Create</span> 
</div>
<table class="display" id="CurriculumDT">
    <thead>
        <tr>
            <th></th>
            <th>Curriculum</th>
            <th>Description</th>
            <th>Academic Year</th>
            <th>Course</th>
            <th>Start Date</th>
            <th>End Date</th>
            
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
</table>
<script src="@Url.Content("~/Content/Js/Curriculum/Index.js")" type="text/javascript"></script>

AteneoHighschool.Admin/Views/Curriculum/_CurriculumItem.cshtml
@model IEnumerable<AteneoHighschool.Data.CurriculumItem>
<div class="ui-grid">
            @if (Model.Any())
            {
                <div id="checkboxes" class="ui-grid-body">
                    <table class="table-striped table-hover" id="FileDT">
                        <thead>
                            <tr class="ui-state-default">
                                <th>Curriculum</th>
                                <th>Description</th>
                                <th>Academic Year</th>
                                <th>Course</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @item.Curriculum.CurriculumName
                                    <td>
                                        @item.Description
                                    </td>
                                    <td>
                                        @item.Curriculum.AcademicYear.AcademicYearName
                                    </td>
                                    <td>
                                        @item.ProficiencyLevel.ProficiencyLevelName
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
            else
            { 
                <div class="ui-widget-content ui-corner-bottom ui-helper-clearfix" style="padding: 0.5em;">
                    No results found
                </div>
            }
        </div> 

AteneoHighschool.Admin/Views/Curriculum/_Detail.cshtml
@model AteneoHighschool.Data.CurriculumVM
<div class="ui-widget ui-widget-content ui-form-body">
    <fieldset>
        @Html.HiddenFor(model => model.Curriculum.CurriculumId)
        <div>
            <label>Proficiency Set: </label>
            @Html.DisplayFor(model => model.Curriculum.CurriculumName)
        </div>
        <div>
            <label>Framework Name: </label>
            @Html.DisplayFor(model => model.Curriculum.CurriculumName)
        </div>
        <div>
            <label>Description: </label>
            @Html.DisplayFor(model => model.Curriculum.Description)
        </div>
        <div>
            <label>Start Date: </label>
            @Html.DisplayFor(model => model.Curriculum.StartDate) 
        </div>
        <div>
            <label>End Date: </label>
            @Html.DisplayFor(model => model.Curriculum.EndDate)
        </div>
    </fieldset>
</div>