AteneoHighschool.Admin/Controllers/CurriculumItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web.Mvc;
using AteneoHighschool.Data;
using AteneoHighschool.DataAccess;

namespace AteneoHighschool.Admin.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class CurriculumItemController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();
        private readonly GenericRoleProvider _roleProvider = new GenericRoleProvider();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetListJson(DataTableParamVM param)
        {
            try
            {
                Thread.Sleep(200);

                string sortProperty;
                string searchText = (!string.IsNullOrEmpty(param.sSearch)) ? param.sSearch : "";

                switch (param.iSortCol_0)
                {
                    case 1: sortProperty = "CurriculumItemName"; break;
                    case 2: sortProperty = "Description"; break;
                    case 3: sortProperty = "Units"; break;
                    case 4: sortProperty = "Sequence"; break;
                    case 5: sortProperty = "ProficiencyLevel.ProficiencyLevelName"; break;
                    default: sortProperty = "ProficiencyLevel.ProficiencyLevelName"; break;
                }

                var curriculumItem =
                    _unitOfWork.CurriculumItemRepository.GetList(
                        q =>
                            q.CurriculumItemName.Contains(searchText) || q.Description.Contains(searchText),
                        iDisplayStart: param.iDisplayStart, iDisplayLength: param.iDisplayLength,
                        sortProperty: sortProperty, sortOrder: param.sSortDir_0, includeProperties: "Curriculum, ProficiencyLevel");

                var recordCount = _unitOfWork.CurriculumItemRepository.Get().Count();

                return Json(new
                {
                    param.sEcho,
                    iTotalRecords = recordCount,
                    iTotalDisplayRecords = recordCount,
                    aaData = curriculumItem
                },
                  JsonRequestBehavior.AllowGet);

            }
            catch (ArgumentException ae)
            {
                ModelState.AddModelError("", ae.Message);
                return Json(new { success = false, error = GetErrorsFromModelState() });
            }
        }

        [HttpPost]
        public JsonResult GetListJson(string searchText, int maxResult)
        {
            var curriculumItemList =
                _unitOfWork.CurriculumItemRepository.GetList(
                    q =>
                        q.CurriculumItemName.Contains(searchText) || q.Description.Contains(searchText),
                    iDisplayLength: maxResult)
                    .Select(q => new { id = q.CurriculumItemId, label = q.CurriculumItemName });
            return Json(curriculumItemList);
        }

        public ActionResult Create()
        {
            if (_roleProvider.IsUserInUserRole(User.Identity.Name, "Administrator"))
            {
                var curriculumItem = new CurriculumItem
                {
                    Curriculum = null,
                };
                return PartialView(CurriculumItemVm(curriculumItem));
            }
            ViewBag.ProhibitedMessage = "Sorry! You have no right to create a new Curriculum Item.";
            return PartialView("_Prohibited");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CreateJson(CurriculumItem curriculumItem)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { success = false, error = GetErrorsFromModelState() });
                }

                _unitOfWork.CurriculumItemRepository.Insert(curriculumItem);
                Guid curriculumItemGuid = curriculumItem.CurriculumItemId;
                curriculumItem =
                    _unitOfWork.CurriculumItemRepository.GetOne(q => q.CurriculumItemId == curriculumItemGuid,
                        includeProperties: "Curriculum");

                return
                    Json(
                        new
                        {
                            success = true,
                            message =
                                "You have successfully created a new Curriculum Item : " +
                                curriculumItem.CurriculumItemName
                        });
            }
            catch (ArgumentException ae)
            {
                ModelState.AddModelError("",
                    "Creation of new Curriculum Item failed. Please check if there is already an existing Curriculum Item : " +
                    curriculumItem.CurriculumItemName + "." + ae.Message);
                return Json(new { success = false, error = GetErrorsFromModelState() });
            }
        }

        public ActionResult Edit(Guid id)
        {
            if (_roleProvider.IsUserInUserRole(User.Identity.Name, "Administrator"))
            {
                CurriculumItem curriculumItem =
                    _unitOfWork.CurriculumItemRepository.GetOne(q => q.CurriculumItemId == id,
                        "Curriculum");
                return PartialView(CurriculumItemVm(curriculumItem));
            }
            ViewBag.ProhibitedMessage = "Sorry! You have no right to edit a Curriculum Item.";
            return PartialView("_Prohibited");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult EditJson(CurriculumItem curriculumItem)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { success = false, error = GetErrorsFromModelState() });
                }

                _unitOfWork.CurriculumItemRepository.Update(curriculumItem);

                return
                    Json(
                        new
                        {
                            success = true,
                            message =
                                "You have successfully edited a Curriculum Item : " + curriculumItem.CurriculumItemName
                        });
            }
            catch (ArgumentException ae)
            {
                ModelState.AddModelError("",
                    ae.Message + "Please check if there is already a Curriculum Item named: " +
                    curriculumItem.CurriculumItemName + ".");
                return Json(new { success = false, error = GetErrorsFromModelState() });
            }
        }

        public ActionResult Delete(Guid id)
        {
            if (_roleProvider.IsUserInUserRole(User.Identity.Name, "Administrator"))
            {
                CurriculumItem curriculumItem =
                    _unitOfWork.CurriculumItemRepository.GetOne(q => q.CurriculumItemId == id);
                return PartialView(CurriculumItemVm(curriculumItem));
            }
            ViewBag.ProhibitedMessage = "Sorry! You have no right to delete a Curriculum Item.";
            return PartialView("_Prohibited");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteJson(CurriculumItem curriculumItem)
        {
            try
            {
                _unitOfWork.CurriculumItemRepository.Delete(curriculumItem);

                return
                    Json(
                        new
                        {
                            success = true,
                            message =
                                "You have successfully deleted a Curriculum Item : " + curriculumItem.CurriculumItemName
                        });
            }
            catch (ArgumentException ae)
            {
                ModelState.AddModelError("", ae.Message);
                return Json(new { success = false, error = GetErrorsFromModelState() });
            }
        }

        public CurriculumItemVM CurriculumItemVm(CurriculumItem curriculumItem)
        {
            var curriculumItemVm = new CurriculumItemVM
            {
                CurriculumItem = curriculumItem,
                CurriculumVM = new CurriculumVM
                {
                    Curriculum = curriculumItem.Curriculum,
                    CurriculumList =
                        new SelectList(_unitOfWork.CurriculumRepository.GetList().OrderBy(c => c.CurriculumName),
                            "CurriculumId", "CurriculumName")
                },
                ProficeLevelVM = new ProficiencyLevelVM
                {
                    ProficiencyLevel = curriculumItem.ProficiencyLevel,
                    ProficiencyLevelList = 
                        new SelectList(_unitOfWork.ProficiencyLevelRepository.GetList().OrderBy(pl => pl.ProficiencyLevelName),
                            "ProficiencyLevelId", "ProficiencyLevelName")
                },
            };
            return curriculumItemVm;
        }

        private IEnumerable<string> GetErrorsFromModelState()
        {
            return ModelState.SelectMany(x => x.Value.Errors.Select(error => error.ErrorMessage));
        }

        protected override void Dispose(bool disposing)
        {
            _unitOfWork.Dispose();
            base.Dispose(disposing);
        }
    }
}

AteneoHighschool.Admin/Views/CurriculumItem/Create.cshtml
@model AteneoHighschool.Data.CurriculumItemVM

@{
    ViewBag.Title = "Create";
}
@using (@Html.BeginForm("CreateJson", "CurriculumItem", FormMethod.Post, new { @id = "CreateCurriculumItemForm" }))
{
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

    <fieldset class="ui-form">

        <div class="editor-label">
            @Html.LabelFor(model => model.CurriculumItem.CurriculumItemName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CurriculumItem.CurriculumItemName)
            @Html.ValidationMessageFor(model => model.CurriculumItem.CurriculumItemName)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.CurriculumItem.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CurriculumItem.Description, "TextArea")
            @Html.ValidationMessageFor(model => model.CurriculumItem.Description)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.CurriculumItem.Units)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CurriculumItem.Units)
            @Html.ValidationMessageFor(model => model.CurriculumItem.Units)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.CurriculumItem.Sequence)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CurriculumItem.Sequence)
            @Html.ValidationMessageFor(model => model.CurriculumItem.Sequence)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CurriculumItem.Curriculum)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.CurriculumItem.CurriculumId, Model.CurriculumVM.CurriculumList, "")
            @Html.ValidationMessageFor(model => model.CurriculumItem.CurriculumId)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.CurriculumItem.ProficiencyLevel)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.CurriculumItem.ProficiencyLevelId, Model.ProficeLevelVM.ProficiencyLevelList, "")
            @Html.ValidationMessageFor(model => model.CurriculumItem.ProficiencyLevelId)
        </div>
    </fieldset>
}
<script src="@Url.Content("~/Content/Js/CurriculumItem/Create.js")" type="text/javascript"></script>

AteneoHighschool.Admin/Views/CurriculumItem/Delete.cshtml
@model AteneoHighschool.Data.CurriculumItemVM

@using (@Html.BeginForm("DeleteJson", "CurriculumItem", FormMethod.Post, new {@id = "DeleteCurriculumItemForm"}))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.CurriculumItem.CurriculumItemId)

    <h3>Are you sure you want to delete this?</h3>
    <fieldset class="ui-form">
        <div>
            Curriculum Item Name :
        </div>
        <div>
            @Html.DisplayFor(model => model.CurriculumItem.CurriculumItemName)
        </div>

        <div>
            Description :
        </div>
        <div>
            @Html.DisplayFor(model => model.CurriculumItem.Description)
        </div>

        <div>
            Unit :
        </div>
        <div>
            @Html.DisplayFor(model => model.CurriculumItem.Units)
        </div>
        
        <div>
            Sequence :
        </div>
        <div>
            @Html.DisplayFor(model => model.CurriculumItem.Sequence)
        </div>
        
        <div>
            Curriculum :
        </div>
        <div>
            @Html.DisplayFor(model => model.CurriculumItem.Curriculum.CurriculumName)
        </div>
    </fieldset>
}
<script src="@Url.Content("~/Content/Js/CurriculumItem/Delete.js")" type="text/javascript"></script>

AteneoHighschool.Admin/Views/CurriculumItem/Edit.cshtml
@model AteneoHighschool.Data.CurriculumItemVM

@{
    ViewBag.Title = "Edit";
}

@using (@Html.BeginForm("EditJson", "CurriculumItem", FormMethod.Post, new { @id = "EditCurriculumItemForm" }))
{
         @Html.AntiForgeryToken()
         @Html.ValidationSummary(true)
         @Html.HiddenFor(model => model.CurriculumItem.CurriculumItemId)
         @Html.HiddenFor(model => model.CurriculumVM.Curriculum.CurriculumId)

    <fieldset class="ui-form">

        <div class="editor-label">
            @Html.LabelFor(model => model.CurriculumItem.CurriculumItemName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CurriculumItem.CurriculumItemName)
            @Html.ValidationMessageFor(model => model.CurriculumItem.CurriculumItemName)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.CurriculumItem.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CurriculumItem.Description, "TextArea")
            @Html.ValidationMessageFor(model => model.CurriculumItem.Description)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.CurriculumItem.Units)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CurriculumItem.Units)
            @Html.ValidationMessageFor(model => model.CurriculumItem.Units)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.CurriculumItem.Sequence)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CurriculumItem.Sequence)
            @Html.ValidationMessageFor(model => model.CurriculumItem.Sequence)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CurriculumItem.Curriculum)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.CurriculumItem.Curriculumid, Model.CurriculumVM.CurriculumList, "")
            @Html.ValidationMessageFor(model => model.CurriculumItem.Curriculumid)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.CurriculumItem.ProficiencyLevel)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.CurriculumItem.ProficiencyLevelId, Model.ProficeLevelVM.ProficiencyLevelList, "")
            @Html.ValidationMessageFor(model => model.CurriculumItem.ProficiencyLevelId)
        </div>
    </fieldset>
}
<script src="@Url.Content("~/Content/Js/CurriculumItem/Edit.js")" type="text/javascript"></script>

AteneoHighschool.Admin/Views/CurriculumItem/Index.cshtml
@{
    ViewBag.Title = "CURRICULUM ITEM MANAGEMENT";
}
<h2>@ViewBag.Title</h2>
<div>
    <span data-dialog-title="Create Curriculum Item" data-url="CurriculumItem/Create" data-id="CreateCurriculumItemDialog" class="uiButton" data-process-button="Create" onclick="loadAndShowDialog($(this))">Create</span> 
</div>
<table class="display" id="CurriculumItemDT">
    <thead>
        <tr>
            <th></th>
            <th>Topic</th>
            <th>Description</th>
            <th>Units</th>
            <th>Sequence</th>
            <th>Subject</th>
            <th>Proficiency Level</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
</table>
<script src="@Url.Content("~/Content/Js/CurriculumItem/Index.js")" type="text/javascript"></script>